postgresql_version: 14
postgresql_data_dir: /var/lib/postgresql/14/main
replication_user: replicator
replication_password: "SuperSecurePass"
primary_host: "{{ hostvars['master-db']['private_ip'] }}"
secondary_host: "{{ hostvars['replica-db']['private_ip'] }}"