- name: Install ACL package
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: yes

- name: Ensure PostgreSQL is installed
  apt:
    name:
      - "postgresql-14"
      - "python3-psycopg2"
    state: present
    update_cache: yes

- name: Check if PostgreSQL cluster exists
  shell: pg_lsclusters | awk 'NR>1 {print $1, $2}'
  register: pg_clusters
  changed_when: false
